# Generated by Django 4.1.7 on 2023-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=19999, max_digits=10, verbose_name='зарплата'),
        ),
    ]
