# Generated by Django 4.1.7 on 2023-03-06 13:46

import apps.workers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_workertimetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workertimetable',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('objects', apps.workers.models.WorkersManager()),
            ],
        ),
    ]
