# Generated by Django 4.1.7 on 2023-02-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_unique_together_room_unique_room_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_room_number',
        ),
    ]
