# Generated by Django 4.1.7 on 2023-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_unique_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='square',
            field=models.FloatField(blank=True, null=True, verbose_name='площадь'),
        ),
    ]
