# Generated by Django 4.1.7 on 2023-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='square',
            field=models.FloatField(null=True, verbose_name='площадь'),
        ),
    ]
