# Generated by Django 4.1.7 on 2023-02-22 13:10

import apps.rooms.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стандартная цена')),
                ('prepayment_percent', models.FloatField(verbose_name='предоплата')),
                ('refund_percent', models.FloatField(verbose_name='возврат')),
                ('main_photo', models.ImageField(upload_to=apps.rooms.utils.build_photo_path)),
                ('rooms_count', models.SmallIntegerField(verbose_name='кол-во комнат')),
                ('floors', models.SmallIntegerField(verbose_name='этажей')),
                ('beds', models.SmallIntegerField(verbose_name='спальных мест')),
                ('square', models.FloatField(verbose_name='площадь')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыто')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='default_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='room',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='room',
            name='main_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='prepayment_percent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='refund_percent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='square',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.SmallIntegerField(default=1, verbose_name='номер комнаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', related_query_name='room', to='rooms.roomcategory'),
        ),
    ]
