# Generated by Django 4.1.7 on 2023-02-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomcategory_alter_room_options_remove_room_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', related_query_name='room', to='rooms.roomcategory'),
        ),
    ]
