# Generated by Django 4.1.7 on 2023-02-23 12:30

import apps.core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='порядковый номер')),
                ('path', models.ImageField(upload_to=apps.core.utils.build_photo_path)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='rooms.roomcategory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('room_category', 'order')},
            },
        ),
    ]
