# Generated by Django 4.1.7 on 2023-02-23 14:04

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=apps.core.utils.build_photo_path, verbose_name='фото'),
        ),
    ]
