# Generated by Django 4.1.7 on 2023-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('rooms', '0010_alter_photo_unique_together_alter_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', related_query_name='room', to='tags.tag', verbose_name='теги'),
        ),
    ]
