# Generated by Django 4.1.7 on 2023-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_roomcategory_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='room',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='доступно'),
        ),
    ]
