# Generated by Django 4.1.7 on 2023-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_remove_room_is_hidden_room_is_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_enable',
        ),
        migrations.AddField(
            model_name='room',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='скрыто'),
        ),
    ]
