# Generated by Django 4.1.7 on 2023-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_remove_room_is_enable_room_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_hidden',
        ),
    ]
