# Generated by Django 4.1.7 on 2023-02-24 13:30

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
