# Generated by Django 4.1.7 on 2023-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Доп. информация'),
        ),
    ]
