# Generated by Django 4.1.7 on 2023-03-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_deleted',
        ),
    ]
