# Generated by Django 4.1.7 on 2023-02-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
