# Generated by Django 4.1.7 on 2023-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_purchase_prepayment_alter_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='start',
            field=models.DateField(),
        ),
    ]
