# Generated by Django 4.1.7 on 2023-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_purchase_end_alter_purchase_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='start',
            field=models.DateField(),
        ),
    ]
